#!/usr/bin/env bash
# Idempotent repository bootstrap for the Cloud Agent environment.
# Installs system + JS dependencies and generates the Prisma client.
# Runtime services (Postgres, dev server) are started by start.sh / terminals.
set -euo pipefail

cd "$(dirname "$0")/.."

# --- System dependency: PostgreSQL server + client (stable, idempotent) ---
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  echo "[install] Installing PostgreSQL..."
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
else
  echo "[install] PostgreSQL already installed."
fi

# --- Local environment file (never overwrite user-provided secrets) ---
if [ ! -f .env ]; then
  echo "[install] Writing default .env for local development."
  cat > .env <<'ENV'
# Local development environment (generated by .cursor/install.sh).
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/semester_planner?schema=public"

# Supabase auth. Project ref matches the JWKS URL hardcoded in proxy.ts.
# Provide a real publishable key (via Cursor Secrets) to exercise full auth.
NEXT_PUBLIC_SUPABASE_URL="https://wqfhplpstiybpskszzxe.supabase.co"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY="sb_publishable_placeholder_dev_key"

NEXT_PUBLIC_APP_URL="http://localhost:3000"

# Optional integrations (PDF import via Gemini, email reminders via Resend).
GEMINI_API_KEY=""
GOOGLE_API_KEY=""
RESEND_API_KEY=""
RESEND_FROM_EMAIL="onboarding@resend.dev"
CRON_SECRET="dev-cron-secret"
ENV
else
  echo "[install] .env already present; leaving it untouched."
fi

# --- JavaScript dependencies ---
echo "[install] Installing npm dependencies..."
npm ci

# --- Prisma client generation (source-derived, belongs in install) ---
echo "[install] Generating Prisma client..."
npx prisma generate

echo "[install] Done."
